# Directories
basedir: ".."
refdir: "ref/"
fastqdir: "rawData/"
fastqcdir: "rawData/QC/"
bamdir: "alignment/"
analysisdir: "analysis/"

# Samples
# Note: `samples` values have to match `units` keys
# `samples` keys have to match condition/treatment of `samples` values
samples:
        WT:
                IP:
                        - IP_WT_rep1
                        - IP_WT_rep2
                        - IP_WT_rep3
                control:
                        - control_WT_rep1
        PreMal:
                IP:
                        - IP_PreMal_rep1
                        - IP_PreMal_rep2
                        - IP_PreMal_rep3
                control:
                        - control_PreMal_rep1
        Mal:
                IP:
                        - IP_Mal_rep1
                        - IP_Mal_rep2
                        - IP_Mal_rep3
                control:
                        - control_Mal_rep1


# Units
# Note: `units` keys have to match `samples` values
units:
        control_WT_rep1:
                - 140120_SN1055_0187_AC2RPNACXX/Sample_WT-input/WT-input_CAGATC_L008_R1_001.fastq.gz
                - 140120_SN1055_0187_AC2RPNACXX/Sample_WT-input/WT-input_CAGATC_L008_R2_001.fastq.gz
        control_PreMal_rep1:
                - 140704_SN1055_0211_AH9WAAADXX/Sample_Premal-input-repeat/Premal-input-repeat_ATCACG_L002_R1_001.fastq.gz
                - 140704_SN1055_0211_AH9WAAADXX/Sample_Premal-input-repeat/Premal-input-repeat_ATCACG_L002_R2_001.fastq.gz
        control_Mal_rep1:
                - 140120_SN1055_0187_AC2RPNACXX/Sample_Mal-input/Mal-input_ACTTGA_L008_R1_001.fastq.gz
                - 140120_SN1055_0187_AC2RPNACXX/Sample_Mal-input/Mal-input_ACTTGA_L008_R2_001.fastq.gz
        IP_WT_rep1:
                - 140827_SN1055_0223_AHAC84ADXX/Sample_WT-R1/WT-R1_CGATGT_L001_R1_001.fastq.gz
                - 140827_SN1055_0223_AHAC84ADXX/Sample_WT-R1/WT-R1_CGATGT_L001_R2_001.fastq.gz
        IP_WT_rep2:
                - 140827_SN1055_0223_AHAC84ADXX/Sample_WT-R1-2/WT-R1-2_TAGCTT_L001_R1_001.fastq.gz
                - 140827_SN1055_0223_AHAC84ADXX/Sample_WT-R1-2/WT-R1-2_TAGCTT_L001_R2_001.fastq.gz
        IP_WT_rep3:
                - 140120_SN1055_0187_AC2RPNACXX/Sample_WT1/WT1_ATCACG_L006_R1_001.fastq.gz
                - 140120_SN1055_0187_AC2RPNACXX/Sample_WT1/WT1_ATCACG_L006_R2_001.fastq.gz
        IP_PreMal_rep1:
                - 140827_SN1055_0223_AHAC84ADXX/Sample_Premal-R1/Premal-R1_TGACCA_L001_R1_001.fastq.gz
                - 140827_SN1055_0223_AHAC84ADXX/Sample_Premal-R1/Premal-R1_TGACCA_L001_R2_001.fastq.gz
        IP_PreMal_rep2:
                - 140120_SN1055_0187_AC2RPNACXX/Sample_PreM1/PreM1_CGATGT_L006_R1_001.fastq.gz
                - 140120_SN1055_0187_AC2RPNACXX/Sample_PreM1/PreM1_CGATGT_L006_R2_001.fastq.gz
        IP_PreMal_rep3:
                - 150319_SN1055_0254_AHHFWJADXX/Sample_Prem-RR1/Prem-RR1_ACAGTG_merged_R1_001.fastq.gz
                - 150319_SN1055_0254_AHHFWJADXX/Sample_Prem-RR1/Prem-RR1_ACAGTG_merged_R2_001.fastq.gz
        IP_Mal_rep1:
                - 140827_SN1055_0223_AHAC84ADXX/Sample_Mal-R1/Mal-R1_CAGATC_L001_R1_001.fastq.gz
                - 140827_SN1055_0223_AHAC84ADXX/Sample_Mal-R1/Mal-R1_CAGATC_L001_R2_001.fastq.gz
        IP_Mal_rep2:
                - 140120_SN1055_0187_AC2RPNACXX/Sample_Mal1/Mal1_TTAGGC_L006_R1_001.fastq.gz
                - 140120_SN1055_0187_AC2RPNACXX/Sample_Mal1/Mal1_TTAGGC_L006_R2_001.fastq.gz
        IP_Mal_rep3:
                - 150319_SN1055_0254_AHHFWJADXX/Sample_Mal-RR1/Mal-RR1_TGACCA_merged_R1_001.fastq.gz
                - 150319_SN1055_0254_AHHFWJADXX/Sample_Mal-RR1/Mal-RR1_TGACCA_merged_R2_001.fastq.gz


# Reference sequence
reference:
    id: "GRCh38+rDNA_repeat"
    filename: "GRCh38+rDNA_repeat.fa"
    gtf: "GRCh38+rDNA_repeat.gtf"
    bed_RefSeq: "GRCh38_RefSeq_genes.bed"
    bed: "GRCh38+rDNA_repeat.bed.gz"


# fastqc parameters
fastqc:
    cmd: "fastqc"


# bowtie2-build parameters
bowtie2-build:
    cmd: "bowtie2-build"


# bowtie2 parameters
bowtie2:
    cmd: "bowtie2"
    in_fmt: "-q"
    phred: "--phred33"
    maxins: 500
    mismatch: 0
    threads: 6


# bwa-mem parameters
bwa-mem:
    cmd: "bwa-mem"


# samtools parameters
samtools:
    cmd: "samtools"


# picard parameters
picard:
    cmd: "java -jar ~/Programs/picard.jar"


# QualiMap parameters
qualimap:
    cmd: "~/Programs/qualimap_v2.2.1/qualimap"


# bedtools parameters
bedtools:
    cmd: "bedtools"
    window_size: 10000
    window_step: 1000


# deeptools parameters
deeptools:
    ignore_for_normalisation:
        - "MT"
        - "X"
        - "Y"
        - "U13369.1"
    cm_upstream: 2000
    cm_downstream: 2000
    binsize: 10
    threads: 6
    scale_method: "readCount"
    bamCompare_specific_args:
#        - "--sampleLength 5000"


# MACS2 parameters
# Note: Even though macs2 accepts gsize = mm, gsize needs
# to be a numeric for further downstream bash maths
macs2:
    gsize: 1.87e9
    qvalue: 0.05
    format: "BAMPE"
